In [2]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
count = CountVectorizer()
docs = np.array([
    'Słońce jest dziś promienne',
    'Pogoda jest dziś wiosenna',
    'Słońce jest dziś promienne i pogoda jest dziś wiosenna a jeden i jeden to jest dwa'
])

In [26]:
bag = count.fit_transform(docs)

In [27]:
print(count.vocabulary_)

{'słońce': 6, 'jest': 3, 'dziś': 1, 'promienne': 5, 'pogoda': 4, 'wiosenna': 8, 'jeden': 2, 'to': 7, 'dwa': 0}


In [29]:
print(bag.toarray())

[[0 1 0 1 0 1 1 0 0]
 [0 1 0 1 1 0 0 0 1]
 [1 2 2 3 1 1 1 1 1]]


In [30]:
from sklearn.feature_extraction.text import TfidfTransformer

In [31]:
tfidf = TfidfTransformer()

In [32]:
np.set_printoptions(precision=2)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.   0.43 0.   0.43 0.   0.56 0.56 0.   0.  ]
 [0.   0.43 0.   0.43 0.56 0.   0.   0.   0.56]
 [0.28 0.33 0.56 0.49 0.21 0.21 0.21 0.28 0.21]]


In [21]:
count = CountVectorizer(ngram_range=(2, 2))
docs = np.array([
    'Słońce jest dziś promienne',
    'Pogoda jest dziś wiosenna',
    'Słońce jest dziś promienne i pogoda jest dziś wiosenna a jeden i jeden to jest dwa'
])

In [22]:
bag = count.fit_transform(docs)

In [23]:
print(count.vocabulary_)

{'słońce jest': 8, 'jest dziś': 5, 'dziś promienne': 0, 'pogoda jest': 6, 'dziś wiosenna': 1, 'promienne pogoda': 7, 'wiosenna jeden': 10, 'jeden jeden': 2, 'jeden to': 3, 'to jest': 9, 'jest dwa': 4}
